// app
export const OPEN_OR_CLOSE_NAV_DRAWER = 'OPEN_OR_CLOSE_NAV_DRAWER';
export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';

// realtime
export const UPDATE_PEERCACHE_PERFORMANCE = 'UPDATE_PEERCACHE_PERFORMANCE';
export const UPDATE_ZERO_TIME_SYNC_PERFORMANCE = 'UPDATE_ZERO_TIME_SYNC_PERFORMANCE';

// settings
export const SET_CURRENT_VCNC = 'SET_CURRENT_VCNC';
export const SET_CURRENT_VTRQ = 'SET_CURRENT_VTRQ';