export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

// app
export const OPEN_OR_CLOSE_NAV_DRAWER = 'OPEN_OR_CLOSE_NAV_DRAWER';
export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';

// settings
export const SET_CURRENT_VTRQ = 'SET_CURRENT_VTRQ';