#
#  Configuration for vcnc
#
server:
  #
  #  The port on which the server listens.  This value may be overridden by 
  #  the VELSTOR_VCNC_PORT environment variable.
  port: 6130
  #
  #  The network interface on which the server listens. If 'all', the server
  #  listens on all interfaces. (Value is currently ignored; server listens on all
  #  interfaces)
  interface: all
  #
  #  The period (1/rate) at which to poll the vtrq for storage statistics, in ms.
  #  This value may be overridden by the VELSTOR_VCNC_VTRQ_POLL_PERIOD_SEC
  #  environment variable.
  #
  #  A rate of a few seconds is intended for customer demo, not production.
  #
  vtrqPollPeriod: 20000

fulfill202:
  #
  #  The URL published in the 'Location' header, where the temporary fulfillment
  #  resource is available.  The full 'Location' url is
  #  `${baseUrl}${route}/${id}.  If unset, the baseUrl is set to
  #  `http://${hostname}:${port}`
  # baseUrl: http://localhost:5500
  #
  #  The endpoint relative to the baseUrl where the fulfillment controller
  #  listens.
  route: /_fulfill
  #
  #  The number of seconds, after the operation completes, that the results
  #  of the operation remain available at the temporary url.
  expires: 600
  #
  #  The number of seconds, once a request is received, after which the 202
  #  response is issued.
  response: 1

mockSampler:
  #
  #  The maximum number of samples stored.
  maxEntries: 100
  #
  #  The RethinkDB table where the real-time dashboard data is stored.
  table: mockSampler
  #
  #  The period (1/rate) of the data in ms
  period: 2000

vcncSampler:
  #
  #  The maximum number of samples stored in rethinkdb
  maxEntries: 100
  #
  #  The maximum number of beans to collect messages
  maxBins: 100
  #
  #  The RethinkDB table where the real-time dashboard data is stored.
  table: vdasampler
  #
  #  The period (1/rate) of the data in ms
  period: 5000
  #
  #  The period extension in ms to prevent data loss, ms
  latency: 35000
  #
  #  The IP address (or hostname) on which to listen for vda posts.
  #  0.0.0.0 listens on all interfaces.
  hostname: 0.0.0.0
  #
  #  The port at which to listen for vda posts.
  port: 6159 

peercache:
  #
  #  The /vtrq/... endpoints specify the vTRQ ID as part of the request.
  #  This vTRQ ID is used by internal vCNC operations.
  #  vTRQ IDs are associated with host:port in config/vcnc-pepsis.conf
  vtrq_id: 0

redis:
  #
  #  Connection information for the Redis client.  See
  #  https://github.com/luin/ioredis/blob/master/API.md#new_Redis.
  #
  #  The Redis server itself is configured separately.  The two configurations
  #  must match where they intersect.
  connection:
    #
    #  Port of the Redis server.  Redis default is 6379
    port: 6379
    #
    #  Host of the Redis server.  Redis default is 'localhost'
    host: localhost
    #
    #  When the Redis server is on the same machine as vCNC, the best performance
    #  may be achieved by connection over a socket.
    # path: /tmp/vcnc-redis.sock
    #
    #  Redis transparently prepends this prefix to every key.  Its purpose is to
    #  avoid conflicts with other software, including another vcnc, which might
    #  be using the same Redis instance.
    keyPrefix: vcnc
    #
    #  An alternative way to isolate vcnc instances is by specifying a database
    #  number.  Valid values are between 0 and 15, inclusive.  Default is 0
    db: 0

rethinkdb:
  #
  #  Connection information for the RethinkDB client.  See
  #  https://www.rethinkdb.com/api/javascript/
  #
  #  The RethinkDB server itself is configured separately.  The two configurations
  #  must match where they intersect.
  connection:
    #
    # The host to connect to.
    # May be overridden by VELSTOR_VCNC_RETHINKDB_HOST
    host: localhost
    #
    # The port to connect on.
    port: 28015
    #
    # The default database
    # May be overridden by VELSTOR_VCNC_RETHINKDB_DB
    db: vcnc_rest
    #
    # The user account to connect as
    user: admin
    #
    # The password for the user account to connect as
    password: ''
    #
    # Timeout period in seconds for the connection to be opened.
    #
    timeout: 20
    # A hash of options to support SSL connections.

test:
  #
  #  Introduces seconds of latency into the (apparent) response time of the vtrq.
  #  Only for testing; production deployments should use value 0.
  latency: 0
  #
  #  If truthy, enables the job grid API.  Should be false for production
  enable_grid_jobs: 1

web:
  #
  #  If true, statically serve the web-based admin console
  #  May be overridden by VELSTOR_VCNC_WEB_ENABLE
  enabled: true
  #
  #  Serve the console at this offset from server.port
  #  If you change this you must also change vcnc-web/src/lib/restHost.js
  offset: -10
